name: Python Package using UV

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          pip install uv
          echo "UV version: $(uv --version)"

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          uv pip install flake8
          uv pip run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          uv pip run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          uv pip install pytest
          uv pip run pytest
